// Render every page of a multi-page draw.io diagram to PNG.
//
// Confluence stores a server-rendered preview PNG only for a diagram's FIRST
// page, so a multi-page diagram (each page = a "slide") loses pages 2..N when we
// localize its single preview. To recover them we render the diagram ourselves:
// split the `.drawio` mxfile into one single-page mxfile per `<diagram>`, load
// draw.io's static viewer in headless Chromium, and screenshot each page.
//
// Chromium is provisioned exactly like react-demo.ts — playwright pinned into an
// isolated runner dir outside the pnpm workspace, chromium fetched into the
// shared user cache on first use (a no-op afterwards). Fully local: only the
// viewer JS is fetched from the CDN; the diagram data never leaves this machine.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';

const PLAYWRIGHT_VERSION = '1.54.2';
const VIEWER_URL = 'https://viewer.diagrams.net/js/viewer-static.min.js';

function execBuffered(
  cmd: string,
  args: string[],
  opts: { cwd?: string; timeout?: number },
): Promise<{ ok: boolean; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    execFile(
      cmd,
      args,
      { cwd: opts.cwd, timeout: opts.timeout ?? 120_000, maxBuffer: 16 * 1024 * 1024, env: process.env },
      (err, stdout, stderr) => resolve({ ok: !err, stdout: String(stdout), stderr: String(stderr) }),
    );
  });
}

let ensured: Promise<string> | null = null;
/** Provision (once) the playwright runner + chromium; returns the runner dir. */
function ensureRunner(runtimeDataDir: string): Promise<string> {
  if (ensured) return ensured;
  ensured = (async () => {
    const runnerDir = path.join(runtimeDataDir, 'drawio-render-runner');
    await fs.promises.mkdir(runnerDir, { recursive: true });
    await fs.promises.writeFile(
      path.join(runnerDir, 'package.json'),
      JSON.stringify({ name: 'od-drawio-render-runner', private: true, dependencies: { playwright: PLAYWRIGHT_VERSION } }, null, 2),
    );
    if (!fs.existsSync(path.join(runnerDir, 'node_modules', 'playwright', 'package.json'))) {
      const r = await execBuffered('npm', ['install', '--no-audit', '--no-fund', '--loglevel=error'], { cwd: runnerDir, timeout: 5 * 60_000 });
      if (!r.ok) throw new Error(`npm install playwright failed:\n${(r.stderr || r.stdout).split('\n').slice(-6).join('\n')}`);
    }
    const pwBin = path.join(runnerDir, 'node_modules', '.bin', 'playwright');
    const r2 = await execBuffered(pwBin, ['install', 'chromium'], { cwd: runnerDir, timeout: 10 * 60_000 });
    if (!r2.ok) throw new Error(`playwright install chromium failed:\n${(r2.stderr || r2.stdout).split('\n').slice(-6).join('\n')}`);
    return runnerDir;
  })().catch((err) => {
    ensured = null; // let a later call retry after a transient failure
    throw err;
  });
  return ensured;
}

/** Split a draw.io mxfile into one single-page mxfile per `<diagram>` element,
 *  preserving each diagram's attributes/content (compressed or plain). */
export function splitMxfilePages(xml: string): string[] {
  const header = /<mxfile\b[^>]*>/i.exec(xml);
  const open = header ? header[0] : '<mxfile>';
  const pages: string[] = [];
  for (const m of xml.matchAll(/<diagram\b[^>]*>[\s\S]*?<\/diagram>/gi)) {
    pages.push(`${open}${m[0]}</mxfile>`);
  }
  // Self-closing <diagram .../> (rare) or a single un-tagged model.
  if (pages.length === 0) pages.push(xml);
  return pages;
}

const RUNNER_MJS = String.raw`// GENERATED by open-design (drawio-render.ts) — do not edit.
import { createRequire } from 'node:module';
import { promises as fsp } from 'node:fs';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const cfg = JSON.parse(await fsp.readFile(process.argv[2], 'utf8'));
const browser = await chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage'] });
try {
  const page = await browser.newPage({ deviceScaleFactor: 2 });
  await page.setContent(
    '<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{margin:0;background:#fff}.mxgraph{display:inline-block;background:#fff;padding:8px}</style></head>' +
      '<body><script src="' + cfg.viewerUrl + '"></' + 'script></body></html>',
    { waitUntil: 'load', timeout: 60000 },
  );
  await page.waitForFunction(() => !!window.GraphViewer, null, { timeout: 30000 });
  // Build one .mxgraph div per page, then let the viewer render them all.
  await page.evaluate((mxfiles) => {
    for (let i = 0; i < mxfiles.length; i++) {
      const d = document.createElement('div');
      d.className = 'mxgraph';
      d.id = 'g' + i;
      d.setAttribute('data-mxgraph', JSON.stringify({ xml: mxfiles[i], toolbar: null, lightbox: false, nav: false, resize: true, border: 8 }));
      document.body.appendChild(d);
    }
    window.GraphViewer.processElements();
  }, cfg.mxfiles);
  await page
    .waitForFunction((n) => document.querySelectorAll('.mxgraph svg').length >= n, cfg.mxfiles.length, { timeout: 30000 })
    .catch(() => {});
  await page.waitForTimeout(400);
  const out = [];
  for (let i = 0; i < cfg.outPaths.length; i++) {
    const el = await page.$('#g' + i);
    if (!el) { out.push(false); continue; }
    try { await el.screenshot({ path: cfg.outPaths[i] }); out.push(true); }
    catch { out.push(false); }
  }
  await fsp.writeFile(cfg.resultPath, JSON.stringify(out));
} finally {
  await browser.close();
}
`;

/** Render each page of a draw.io mxfile to a PNG at the matching outPath.
 *  Returns the subset of outPaths that were written. Best-effort — throws only
 *  if Chromium can't be provisioned; per-page failures are skipped. */
export async function renderDrawioPages(
  xml: string,
  outPaths: string[],
  runtimeDataDir: string,
): Promise<string[]> {
  const mxfiles = splitMxfilePages(xml);
  if (mxfiles.length !== outPaths.length) {
    // Caller sized outPaths to the page count; guard against a mismatch.
    const n = Math.min(mxfiles.length, outPaths.length);
    mxfiles.length = n;
    outPaths = outPaths.slice(0, n);
  }
  const runnerDir = await ensureRunner(runtimeDataDir);
  const runnerMjs = path.join(runnerDir, 'render-drawio.mjs');
  await fs.promises.writeFile(runnerMjs, RUNNER_MJS);
  const cfgPath = path.join(await fs.promises.mkdtemp(path.join(os.tmpdir(), 'od-drawio-')), 'cfg.json');
  const resultPath = `${cfgPath}.result.json`;
  await fs.promises.writeFile(
    cfgPath,
    JSON.stringify({ viewerUrl: VIEWER_URL, mxfiles, outPaths, resultPath }),
  );
  const r = await execBuffered(process.execPath, [runnerMjs, cfgPath], { cwd: runnerDir, timeout: 4 * 60_000 });
  if (!r.ok) throw new Error(`drawio render runner failed:\n${(r.stderr || r.stdout).split('\n').slice(-8).join('\n')}`);
  let flags: boolean[] = [];
  try {
    flags = JSON.parse(await fs.promises.readFile(resultPath, 'utf8')) as boolean[];
  } catch {
    flags = outPaths.map(() => false);
  }
  return outPaths.filter((_, i) => flags[i]);
}
