// @open-design/figma-h2d — clean-room CSS default tables.
// Factual UA/initial CSS values (as resolved by Chromium getComputedStyle) used to drop
// default-valued properties when serializing. Not Figma source; reproduced from CSS specs +
// observed Chromium computed-style defaults. See specs/current/h2d-serializer-spec.md §3.

/** prop -> Chromium computed default. A property is kept only when its computed value differs. */
export const STYLE_DEFAULTS: Readonly<Record<string, string>> = Object.freeze({
  alignContent: "normal",
  alignItems: "normal",
  alignSelf: "auto",
  aspectRatio: "auto",
  backdropFilter: "none",
  backgroundAttachment: "scroll",
  backgroundBlendMode: "normal",
  backgroundClip: "border-box",
  backgroundColor: "rgba(0, 0, 0, 0)",
  backgroundImage: "none",
  backgroundOrigin: "padding-box",
  backgroundPositionX: "0%",
  backgroundPositionY: "0%",
  backgroundRepeat: "repeat",
  backgroundSize: "auto",
  borderBottomColor: "rgb(0, 0, 0)",
  borderBottomLeftRadius: "0px",
  borderBottomRightRadius: "0px",
  borderBottomStyle: "none",
  borderBottomWidth: "0px",
  borderCollapse: "separate",
  borderImageOutset: "0",
  borderImageRepeat: "stretch",
  borderImageSlice: "100%",
  borderImageSource: "none",
  borderImageWidth: "1",
  borderLeftColor: "rgb(0, 0, 0)",
  borderLeftStyle: "none",
  borderLeftWidth: "0px",
  borderRightColor: "rgb(0, 0, 0)",
  borderRightStyle: "none",
  borderRightWidth: "0px",
  borderSpacing: "0px",
  borderTopColor: "rgb(0, 0, 0)",
  borderTopLeftRadius: "0px",
  borderTopRightRadius: "0px",
  borderTopStyle: "none",
  borderTopWidth: "0px",
  bottom: "auto",
  boxShadow: "none",
  boxSizing: "content-box",
  clear: "none",
  clip: "auto",
  clipPath: "none",
  clipRule: "nonzero",
  color: "rgb(0, 0, 0)",
  colorScheme: "normal",
  columnCount: "auto",
  columnFill: "balance",
  columnGap: "normal",
  columnRuleColor: "rgb(0, 0, 0)",
  columnRuleStyle: "none",
  columnRuleWidth: "0px",
  columnSpan: "none",
  columnWidth: "auto",
  contain: "none",
  containerType: "normal",
  content: "normal",
  contentVisibility: "visible",
  display: "",
  filter: "none",
  flexBasis: "auto",
  flexDirection: "row",
  flexGrow: "0",
  flexShrink: "1",
  flexWrap: "nowrap",
  float: "none",
  fontFamily: "Times",
  fontFeatureSettings: "normal",
  fontKerning: "auto",
  fontOpticalSizing: "auto",
  fontPalette: "normal",
  fontSize: "16px",
  fontSizeAdjust: "none",
  fontStretch: "100%",
  fontStyle: "normal",
  fontWeight: "400",
  gridAutoColumns: "auto",
  gridAutoFlow: "row",
  gridAutoRows: "auto",
  gridColumnEnd: "auto",
  gridColumnStart: "auto",
  gridRowEnd: "auto",
  gridRowStart: "auto",
  gridTemplateAreas: "none",
  gridTemplateColumns: "none",
  gridTemplateRows: "none",
  height: "auto",
  isolation: "auto",
  justifyItems: "normal",
  justifySelf: "auto",
  justifyContent: "normal",
  left: "auto",
  letterSpacing: "normal",
  lineBreak: "auto",
  lineHeight: "normal",
  listStyleImage: "none",
  listStylePosition: "outside",
  listStyleType: "disc",
  marginBottom: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  maxHeight: "none",
  maxWidth: "none",
  minHeight: "auto",
  minWidth: "auto",
  mixBlendMode: "normal",
  objectFit: "fill",
  opacity: "1",
  order: "0",
  outlineColor: "rgb(0, 0, 0)",
  outlineOffset: "0px",
  outlineStyle: "none",
  outlineWidth: "0px",
  overflow: "visible",
  overflowX: "visible",
  overflowY: "visible",
  position: "static",
  paddingBottom: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingTop: "0px",
  quotes: "auto",
  right: "auto",
  rowGap: "normal",
  strokeDasharray: "none",
  strokeDashoffset: "0px",
  strokeLinecap: "butt",
  strokeLinejoin: "miter",
  strokeMiterlimit: "4",
  strokeOpacity: "1",
  strokeWidth: "1px",
  textAlign: "start",
  textDecorationColor: "rgb(0, 0, 0)",
  textDecorationLine: "none",
  textDecorationStyle: "solid",
  textIndent: "0px",
  textShadow: "none",
  textTransform: "none",
  textWrapStyle: "auto",
  top: "auto",
  perspective: "none",
  transform: "none",
  transformOrigin: "auto",
  translate: "none",
  transitionProperty: "all",
  verticalAlign: "baseline",
  visibility: "visible",
  webkitTextFillColor: "",
  whiteSpace: "normal",
  width: "auto",
  willChange: "auto",
  writingMode: "horizontal-tb",
  zIndex: "auto",
  rotate: "none",
  scale: "none",
});

export const STYLE_DEFAULT_ENTRIES = Object.freeze(Object.entries(STYLE_DEFAULTS));

/** camelCase -> kebab (webkit* gets a leading dash), for CSS Typed OM lookups. */
export function toDashProp(prop: string): string {
  const kebab = prop.replace(/([A-Z])/g, "-$1").toLowerCase();
  return prop.startsWith("webkit") ? `-${kebab}` : kebab;
}

export const DASH_PROP: Readonly<Record<string, string>> = Object.freeze(
  Object.fromEntries(Object.keys(STYLE_DEFAULTS).map((p) => [p, toDashProp(p)])),
);

/** SVG presentation attributes baked onto cloned SVG when computed value != default. */
export const SVG_PRESENTATION_DEFAULTS: Readonly<Record<string, string>> = Object.freeze({
  alignmentBaseline: "baseline",
  clip: "auto",
  clipPath: "none",
  clipRule: "nonzero",
  color: "rgb(0, 0, 0)",
  colorInterpolation: "sRGB",
  colorRendering: "auto",
  cursor: "auto",
  direction: "ltr",
  display: "inline",
  dominantBaseline: "auto",
  fill: "rgb(0, 0, 0)",
  fillOpacity: "1",
  fillRule: "nonzero",
  filter: "none",
  floodColor: "rgb(0, 0, 0)",
  floodOpacity: "1",
  imageRendering: "auto",
  letterSpacing: "normal",
  lightingColor: "rgb(255, 255, 255)",
  lineHeight: "normal",
  markerEnd: "none",
  markerMid: "none",
  markerStart: "none",
  mask: "none",
  opacity: "1",
  overflow: "visible",
  paintOrder: "normal",
  shapeRendering: "auto",
  stopColor: "rgb(0, 0, 0)",
  stopOpacity: "1",
  stroke: "none",
  strokeDasharray: "none",
  strokeDashoffset: "0px",
  strokeLinecap: "butt",
  strokeLinejoin: "miter",
  strokeMiterlimit: "4",
  strokeOpacity: "1",
  strokeWidth: "1px",
  textAnchor: "start",
  textDecoration: "none solid rgb(0, 0, 0)",
  textRendering: "auto",
  unicodeBidi: "normal",
  vectorEffect: "none",
  visibility: "visible",
  whiteSpace: "normal",
  writingMode: "horizontal-tb",
});

/** Typed-OM groups (see spec §3.4). */
export const SIZING_PROPS = ["width","height","minWidth","maxWidth","minHeight","maxHeight"] as const;
export const MARGIN_PROPS = ["marginTop","marginRight","marginBottom","marginLeft"] as const;
export const GRID_PROPS = ["gridTemplateColumns","gridTemplateRows","gridColumnStart","gridColumnEnd","gridRowStart","gridRowEnd","columnGap","rowGap","gridAutoFlow","gridTemplateAreas","gridAutoColumns","gridAutoRows"] as const;

export const BORDER_EDGES = [
  { style: "borderTopStyle", width: "borderTopWidth", color: "borderTopColor" },
  { style: "borderRightStyle", width: "borderRightWidth", color: "borderRightColor" },
  { style: "borderBottomStyle", width: "borderBottomWidth", color: "borderBottomColor" },
  { style: "borderLeftStyle", width: "borderLeftWidth", color: "borderLeftColor" },
] as const;

/** Attributes preserved on element nodes (plus any aria-* attribute). */
export const ATTR_ALLOWLIST = new Set(["alt","checked","currentSrc","disabled","for","href","id","multiple","placeholder","poster","readonly","rel","required","role","selected","target","title","type","value"]);

/** input types whose ::placeholder styles are captured. */
export const PLACEHOLDER_INPUT_TYPES = new Set(["text","search","tel","url","email","password","number"]);
