// AUTO-GENERATED by builder. Bundles the verbatim VNPAY component set
// (components/ui + lib/utils + Base UI / radix / lucide) and exposes globals
// for an agent-authored App() to consume via Babel-standalone JSX.
import * as React from "react";
import * as ReactJSXRuntime from "react/jsx-runtime";
import { createRoot } from "react-dom/client";
import * as Lucide from "lucide-react";
import { cn } from "@/lib/utils";

import * as accordion from "@/components/ui/accordion";
import * as alert from "@/components/ui/alert";
import * as alertDialog from "@/components/ui/alert-dialog";
import * as aspectRatio from "@/components/ui/aspect-ratio";
import * as avatar from "@/components/ui/avatar";
import * as badge from "@/components/ui/badge";
import * as breadcrumb from "@/components/ui/breadcrumb";
import * as button from "@/components/ui/button";
import * as card from "@/components/ui/card";
import * as carousel from "@/components/ui/carousel";
import * as checkbox from "@/components/ui/checkbox";
import * as collapsible from "@/components/ui/collapsible";
import * as command from "@/components/ui/command";
import * as dialog from "@/components/ui/dialog";
import * as drawer from "@/components/ui/drawer";
import * as dropdownMenu from "@/components/ui/dropdown-menu";
import * as field from "@/components/ui/field";
import * as form from "@/components/ui/form";
import * as hoverCard from "@/components/ui/hover-card";
import * as input from "@/components/ui/input";
import * as inputGroup from "@/components/ui/input-group";
import * as inputOtp from "@/components/ui/input-otp";
import * as labelMod from "@/components/ui/label";
import * as pagination from "@/components/ui/pagination";
import * as popover from "@/components/ui/popover";
import * as progress from "@/components/ui/progress";
import * as radioGroup from "@/components/ui/radio-group";
import * as scrollArea from "@/components/ui/scroll-area";
import * as select from "@/components/ui/select";
import * as separator from "@/components/ui/separator";
import * as sheet from "@/components/ui/sheet";
import * as skeleton from "@/components/ui/skeleton";
import * as slider from "@/components/ui/slider";
import * as switchComp from "@/components/ui/switch";
import * as table from "@/components/ui/table";
import * as tabs from "@/components/ui/tabs";
import * as textarea from "@/components/ui/textarea";
import * as toggle from "@/components/ui/toggle";
import * as toggleGroup from "@/components/ui/toggle-group";
import * as tooltip from "@/components/ui/tooltip";

const UI: Record<string, unknown> = {};
for (const mod of [
  accordion, alert, alertDialog, aspectRatio, avatar, badge, breadcrumb,
  button, card, carousel, checkbox, collapsible, command, dialog, drawer,
  dropdownMenu, field, form, hoverCard, input, inputGroup, inputOtp, labelMod,
  pagination, popover, progress, radioGroup, scrollArea, select, separator,
  sheet, skeleton, slider, switchComp, table, tabs, textarea, toggle,
  toggleGroup, tooltip,
]) {
  Object.assign(UI, mod);
}

const w = window as unknown as Record<string, unknown>;
w.React = React;
w.ReactJSXRuntime = ReactJSXRuntime;
w.createRoot = createRoot;
w.UI = UI;
w.Lucide = Lucide;
w.cn = cn;
w.__OD_RSHADCN_READY__ = true;
window.dispatchEvent(new Event("od-rshadcn-ready"));
