// GENERATED bởi skills/ux-spec/scripts/gen-wire-doc.mjs — ĐỪNG sửa tay.
// Nguồn: skills/ux-spec/references/wire-registry.json (DSL v2).
// Chạy lại: node skills/ux-spec/scripts/gen-wire-doc.mjs
export const WIRE_DSL_VERSION = 2;

/** slug v2 (lowercase) → render kind mà LeafBody vẽ. */
const SLUG_RENDER: Record<string, string> = {
  "shadcn:heading": "heading",
  "shadcn:text": "text",
  "shadcn:label": "text",
  "layout:sectionlabel": "section",
  "shadcn:link": "link",
  "shadcn:input": "input",
  "shadcn:inputsearch": "search",
  "shadcn:textarea": "textarea",
  "shadcn:select": "select",
  "shadcn:checkbox": "checkbox",
  "shadcn:radiogroup": "radio",
  "shadcn:switch": "toggle",
  "shadcn:slider": "slider",
  "shadcn:inputotp": "otp",
  "shadcn:button": "button",
  "shadcn:badge": "chip",
  "shadcn:togglegroup": "chips",
  "shadcn:tabs": "tabs",
  "shadcn:navigationmenu": "navbar",
  "shadcn:breadcrumb": "breadcrumb",
  "shadcn:pagination": "pagination",
  "shadcn:sidebar": "sidebar",
  "shadcn:accordion": "accordion",
  "shadcn:item": "list",
  "shadcn:table": "table",
  "shadcn:card": "card",
  "data:stat": "stat",
  "shadcn:progress": "progress",
  "data:stepper": "stepper",
  "shadcn:skeleton": "skeleton",
  "shadcn:empty": "empty",
  "shadcn:avatar": "avatar",
  "media:image": "image",
  "shadcn:separator": "divider",
  "shadcn:alert": "alert",
  "layout:spacer": "spacer",
  "mobile:appbar": "appbar",
  "mobile:bottomnav": "bottomnav",
  "mobile:fab": "fab",
  "mobile:navdrawer": "drawer",
  "mobile:actionsheet": "list"
};
/** từ vựng v1 (lowercase) → render kind. Giữ file cũ chạy được, không cần migrate. */
const ALIAS_RENDER: Record<string, string> = {
  "heading": "heading",
  "title": "heading",
  "text": "text",
  "paragraph": "text",
  "content": "text",
  "label": "text",
  "section": "section",
  "sectionlabel": "section",
  "link": "link",
  "anchor": "link",
  "input": "input",
  "textinput": "input",
  "textfield": "input",
  "search": "search",
  "searchbox": "search",
  "textarea": "textarea",
  "select": "select",
  "dropdown": "select",
  "combobox": "select",
  "picker": "select",
  "checkbox": "checkbox",
  "radio": "radio",
  "radiogroup": "radio",
  "toggle": "toggle",
  "switch": "toggle",
  "slider": "slider",
  "range": "slider",
  "otp": "otp",
  "inputotp": "otp",
  "pin": "otp",
  "button": "button",
  "cta": "button",
  "chip": "chip",
  "tag": "chip",
  "badge": "chip",
  "chips": "chips",
  "chipgroup": "chips",
  "togglegroup": "chips",
  "segmented": "chips",
  "tabs": "tabs",
  "tabbar": "tabs",
  "navbar": "navbar",
  "topnav": "navbar",
  "header": "navbar",
  "breadcrumb": "breadcrumb",
  "crumbs": "breadcrumb",
  "pagination": "pagination",
  "pager": "pagination",
  "sidebar": "sidebar",
  "sidenav": "sidebar",
  "accordion": "accordion",
  "collapsible": "accordion",
  "disclosure": "accordion",
  "list": "list",
  "item": "list",
  "listitem": "list",
  "rows": "list",
  "table": "table",
  "datagrid": "table",
  "grid": "table",
  "card": "card",
  "panel": "card",
  "stat": "stat",
  "kpi": "stat",
  "metric": "stat",
  "progress": "progress",
  "progressbar": "progress",
  "stepper": "stepper",
  "steps": "stepper",
  "wizard": "stepper",
  "skeleton": "skeleton",
  "placeholder": "skeleton",
  "loading": "skeleton",
  "empty": "empty",
  "emptystate": "empty",
  "nodata": "empty",
  "avatar": "avatar",
  "profilepic": "avatar",
  "image": "image",
  "illustration": "image",
  "photo": "image",
  "banner": "image",
  "divider": "divider",
  "separator": "divider",
  "hr": "divider",
  "alert": "alert",
  "callout": "alert",
  "toast": "alert",
  "spacer": "spacer",
  "gap": "spacer",
  "appbar": "appbar",
  "topbar": "appbar",
  "bottomnav": "bottomnav",
  "tabbarbottom": "bottomnav",
  "navbottom": "bottomnav",
  "fab": "fab",
  "floatingbutton": "fab",
  "drawer": "drawer",
  "navdrawer": "drawer",
  "sidedrawer": "drawer",
  "actionsheet": "list",
  "sheetactions": "list"
};
/** bất kỳ key nào → slug v2 chính tắc (để hiện trong badge / tooltip). */
const CANONICAL: Record<string, string> = {
  "shadcn:heading": "shadcn:Heading",
  "heading": "shadcn:Heading",
  "title": "shadcn:Heading",
  "shadcn:text": "shadcn:Text",
  "text": "shadcn:Text",
  "paragraph": "shadcn:Text",
  "content": "shadcn:Text",
  "shadcn:label": "shadcn:Label",
  "label": "shadcn:Label",
  "layout:sectionlabel": "layout:SectionLabel",
  "section": "layout:SectionLabel",
  "sectionlabel": "layout:SectionLabel",
  "shadcn:link": "shadcn:Link",
  "link": "shadcn:Link",
  "anchor": "shadcn:Link",
  "shadcn:input": "shadcn:Input",
  "input": "shadcn:Input",
  "textinput": "shadcn:Input",
  "textfield": "shadcn:Input",
  "shadcn:inputsearch": "shadcn:InputSearch",
  "search": "shadcn:InputSearch",
  "searchbox": "shadcn:InputSearch",
  "shadcn:textarea": "shadcn:Textarea",
  "textarea": "shadcn:Textarea",
  "shadcn:select": "shadcn:Select",
  "select": "shadcn:Select",
  "dropdown": "shadcn:Select",
  "combobox": "shadcn:Select",
  "picker": "shadcn:Select",
  "shadcn:checkbox": "shadcn:Checkbox",
  "checkbox": "shadcn:Checkbox",
  "shadcn:radiogroup": "shadcn:RadioGroup",
  "radio": "shadcn:RadioGroup",
  "radiogroup": "shadcn:RadioGroup",
  "shadcn:switch": "shadcn:Switch",
  "toggle": "shadcn:Switch",
  "switch": "shadcn:Switch",
  "shadcn:slider": "shadcn:Slider",
  "slider": "shadcn:Slider",
  "range": "shadcn:Slider",
  "shadcn:inputotp": "shadcn:InputOTP",
  "otp": "shadcn:InputOTP",
  "inputotp": "shadcn:InputOTP",
  "pin": "shadcn:InputOTP",
  "shadcn:button": "shadcn:Button",
  "button": "shadcn:Button",
  "cta": "shadcn:Button",
  "shadcn:badge": "shadcn:Badge",
  "chip": "shadcn:Badge",
  "tag": "shadcn:Badge",
  "badge": "shadcn:Badge",
  "shadcn:togglegroup": "shadcn:ToggleGroup",
  "chips": "shadcn:ToggleGroup",
  "chipgroup": "shadcn:ToggleGroup",
  "togglegroup": "shadcn:ToggleGroup",
  "segmented": "shadcn:ToggleGroup",
  "shadcn:tabs": "shadcn:Tabs",
  "tabs": "shadcn:Tabs",
  "tabbar": "shadcn:Tabs",
  "shadcn:navigationmenu": "shadcn:NavigationMenu",
  "navbar": "shadcn:NavigationMenu",
  "topnav": "shadcn:NavigationMenu",
  "header": "shadcn:NavigationMenu",
  "shadcn:breadcrumb": "shadcn:Breadcrumb",
  "breadcrumb": "shadcn:Breadcrumb",
  "crumbs": "shadcn:Breadcrumb",
  "shadcn:pagination": "shadcn:Pagination",
  "pagination": "shadcn:Pagination",
  "pager": "shadcn:Pagination",
  "shadcn:sidebar": "shadcn:Sidebar",
  "sidebar": "shadcn:Sidebar",
  "sidenav": "shadcn:Sidebar",
  "shadcn:accordion": "shadcn:Accordion",
  "accordion": "shadcn:Accordion",
  "collapsible": "shadcn:Accordion",
  "disclosure": "shadcn:Accordion",
  "shadcn:item": "shadcn:Item",
  "list": "shadcn:Item",
  "item": "shadcn:Item",
  "listitem": "shadcn:Item",
  "rows": "shadcn:Item",
  "shadcn:table": "shadcn:Table",
  "table": "shadcn:Table",
  "datagrid": "shadcn:Table",
  "grid": "shadcn:Table",
  "shadcn:card": "shadcn:Card",
  "card": "shadcn:Card",
  "panel": "shadcn:Card",
  "data:stat": "data:Stat",
  "stat": "data:Stat",
  "kpi": "data:Stat",
  "metric": "data:Stat",
  "shadcn:progress": "shadcn:Progress",
  "progress": "shadcn:Progress",
  "progressbar": "shadcn:Progress",
  "data:stepper": "data:Stepper",
  "stepper": "data:Stepper",
  "steps": "data:Stepper",
  "wizard": "data:Stepper",
  "shadcn:skeleton": "shadcn:Skeleton",
  "skeleton": "shadcn:Skeleton",
  "placeholder": "shadcn:Skeleton",
  "loading": "shadcn:Skeleton",
  "shadcn:empty": "shadcn:Empty",
  "empty": "shadcn:Empty",
  "emptystate": "shadcn:Empty",
  "nodata": "shadcn:Empty",
  "shadcn:avatar": "shadcn:Avatar",
  "avatar": "shadcn:Avatar",
  "profilepic": "shadcn:Avatar",
  "media:image": "media:Image",
  "image": "media:Image",
  "illustration": "media:Image",
  "photo": "media:Image",
  "banner": "media:Image",
  "shadcn:separator": "shadcn:Separator",
  "divider": "shadcn:Separator",
  "separator": "shadcn:Separator",
  "hr": "shadcn:Separator",
  "shadcn:alert": "shadcn:Alert",
  "alert": "shadcn:Alert",
  "callout": "shadcn:Alert",
  "toast": "shadcn:Alert",
  "layout:spacer": "layout:Spacer",
  "spacer": "layout:Spacer",
  "gap": "layout:Spacer",
  "mobile:appbar": "mobile:AppBar",
  "appbar": "mobile:AppBar",
  "topbar": "mobile:AppBar",
  "mobile:bottomnav": "mobile:BottomNav",
  "bottomnav": "mobile:BottomNav",
  "tabbarbottom": "mobile:BottomNav",
  "navbottom": "mobile:BottomNav",
  "mobile:fab": "mobile:Fab",
  "fab": "mobile:Fab",
  "floatingbutton": "mobile:Fab",
  "mobile:navdrawer": "mobile:NavDrawer",
  "drawer": "mobile:NavDrawer",
  "navdrawer": "mobile:NavDrawer",
  "sidedrawer": "mobile:NavDrawer",
  "mobile:actionsheet": "mobile:ActionSheet",
  "actionsheet": "mobile:ActionSheet",
  "sheetactions": "mobile:ActionSheet"
};

export interface ResolvedWireKind {
  /** render kind cho switch trong LeafBody */
  kind: string;
  /** slug v2 chính tắc */
  slug: string;
  /** true khi file dùng từ vựng v1 */
  legacy: boolean;
}

/** Tra slug (v2) hoặc componentType (v1). null = KHÔNG có trong registry →
 *  renderer phải vẽ badge đỏ, không được im lặng ra hộp rỗng. */
export function resolveWireKind(raw?: string | null): ResolvedWireKind | null {
  if (!raw) return null;
  const key = String(raw).toLowerCase();
  const direct = SLUG_RENDER[key];
  if (direct) return { kind: direct, slug: CANONICAL[key] ?? String(raw), legacy: false };
  const alias = ALIAS_RENDER[key];
  if (alias) return { kind: alias, slug: CANONICAL[key] ?? String(raw), legacy: true };
  return null;
}

/** Làm phẳng leaf v2 (`{c, props:{…}}`) về đúng shape phẳng mà renderer đang đọc,
 *  và ánh xạ prop v2 (items/active/block) sang tên v1 (tabs/chips/activeTab/grow). */
export function normalizeWireLeaf<T extends Record<string, unknown>>(node: T): Record<string, unknown> {
  const bag = (node as { props?: Record<string, unknown> }).props;
  const flat: Record<string, unknown> = bag && typeof bag === 'object' ? { ...node, ...bag } : { ...node };
  const items = flat.items;
  if (Array.isArray(items)) {
    if (flat.tabs === undefined) flat.tabs = items;
    if (flat.chips === undefined) flat.chips = items;
    if (flat.navItems === undefined) flat.navItems = items;
  }
  if (typeof flat.active === 'number') {
    if (flat.activeTab === undefined) flat.activeTab = flat.active;
    if (flat.activeStep === undefined) flat.activeStep = flat.active;
  }
  if (flat.block === true && flat.grow === undefined) flat.grow = 1;
  return flat;
}
