import { describe, expect, it } from 'vitest';

import {
  applyConfigEnv,
  resolveOdHomeFromModuleDir,
} from '../src/load-host-config-env.js';

describe('resolveOdHomeFromModuleDir', () => {
  // node:path is platform-native (win32 semantics on a real Windows install,
  // POSIX here) — the directory-count arithmetic below is separator-agnostic,
  // so a POSIX-shaped path exercises the same logic that runs on Windows.
  it('walks up from a dist build to OD_HOME', () => {
    const moduleDir = '/home/user/.open-design/releases/0.8.4/apps/daemon/dist';
    expect(resolveOdHomeFromModuleDir(moduleDir)).toBe('/home/user/.open-design');
  });

  it('walks up from a src (ts-node/dev) build the same way as dist', () => {
    const moduleDir = '/home/user/.open-design/releases/0.8.4/apps/daemon/src';
    expect(resolveOdHomeFromModuleDir(moduleDir)).toBe('/home/user/.open-design');
  });
});

describe('applyConfigEnv', () => {
  it('fills vars missing from the target', () => {
    const target: NodeJS.ProcessEnv = {};
    applyConfigEnv('MEDIA_URL=https://example.com/media\nGOOGLE_CLIENT_ID=abc123\n', target);
    expect(target.MEDIA_URL).toBe('https://example.com/media');
    expect(target.GOOGLE_CLIENT_ID).toBe('abc123');
  });

  it('never overrides a var already present in the target', () => {
    const target: NodeJS.ProcessEnv = { MEDIA_URL: 'https://real-launchd-sourced.example.com' };
    applyConfigEnv('MEDIA_URL=https://from-config-env.example.com\n', target);
    expect(target.MEDIA_URL).toBe('https://real-launchd-sourced.example.com');
  });

  it('skips comments and blank lines from install.sh/install.ps1 output', () => {
    const target: NodeJS.ProcessEnv = {};
    applyConfigEnv(
      '# Generated by deploy/host/install.sh on 2026-08-14T00:00:00Z\n\nOD_PORT=7456\n',
      target,
    );
    expect(target.OD_PORT).toBe('7456');
    expect(Object.keys(target)).toEqual(['OD_PORT']);
  });
});
