// Regenerate the skill runtime from the build-once outputs:
//   builder/dist/components.bundle.js + builder/src/styles/*  →
//   ../assets/runtime/{components.bundle.js,theme.css} + ../assets/shell.html
// Run after `node build.mjs`. The JSON-driven render block lives in
// builder/app-shell-block.jsx (single source); make-shell.mjs assembles the
// same shell.html from existing runtime/ outputs when the bundle is unchanged.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const styles = resolve(here, "src/styles");
const assets = resolve(here, "../assets");
const runtime = resolve(assets, "runtime");
mkdirSync(runtime, { recursive: true });

// 1. Merge token CSS: inline shadcn-tailwind.css into app.css, strip @source
//    (no filesystem in the @tailwindcss/browser engine).
let app = readFileSync(resolve(styles, "app.css"), "utf8");
const shadcn = readFileSync(resolve(styles, "shadcn-tailwind.css"), "utf8");
app = app.replace(
  '@import "./shadcn-tailwind.css";',
  `\n/* ---- inlined shadcn-tailwind.css ---- */\n${shadcn}\n/* ---- end shadcn-tailwind.css ---- */\n`,
);
app = app.replace(/^@source\s+[^;]+;\s*$/gm, "").replace(/\n{3,}/g, "\n\n");
writeFileSync(resolve(runtime, "theme.css"), app);

// 2. Copy the prebuilt bundle into assets (kept beside the shell for diffing).
copyFileSync(resolve(here, "dist/components.bundle.js"), resolve(runtime, "components.bundle.js"));
const bundle = readFileSync(resolve(runtime, "components.bundle.js"), "utf8");

// 3. Read the JSON-driven render block (single source, shared with make-shell.mjs).
const block = readFileSync(resolve(here, "app-shell-block.jsx"), "utf8");

// 3b. VNPAY Glass brand stylesheet (dual-scheme light/dark + glass + control
//     sizing). Inlined so every generated screen gets the brand AND both modes
//     by default. Generated by make-showcase.mjs from verbatim KG tokens.
const glassPath = resolve(assets, "vnpay-glass.css");
const glass = existsSync(glassPath) ? readFileSync(glassPath, "utf8") : "";
if (!glass) console.warn("[gen-runtime] vnpay-glass.css missing — run make-showcase.mjs first (shell will have no light/dark brand).");

// 4. Emit the self-contained shell with bundle + theme + render block inlined.
const html = `<!doctype html>
<html lang="en" class="__OD_SCHEME__">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Artifact — react-shadcn-html (JSON-driven VNPAY screen)</title>

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Bricolage+Grotesque:wght@500;600;650;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />

  <!-- Tailwind v4 in-browser engine (JIT-scans the live DOM, so both the
       verbatim component classes AND any class in screen.json compile). -->
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

  <!-- Verbatim token system (app.css + shadcn-tailwind.css merged, @source
       stripped). Carries the built-in default theme :root values. -->
  <style type="text/tailwindcss">
${app}
  </style>

  <!-- VNPAY Glass brand override (dual-scheme light/dark, KG-resolved). Plain
       CSS placed AFTER theme.css so its :root / html.dark tokens win. -->
  <style>
${glass}
  </style>

  <!-- Babel Standalone: transpiles ONLY the JSON-driven render block below. -->
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>
<body>
  <div id="root"></div>

  <!-- ===================================================================== -->
  <!-- PREBUILT COMPONENT BUNDLE (build-once, do not edit).                  -->
  <!-- Exposes: window.{React, createRoot, UI, Lucide, cn}.                  -->
  <!-- UI holds every export of components/ui/*.tsx (Button, Card, Tabs…).   -->
  <!-- ===================================================================== -->
  <script>
/*__OD_COMPONENT_BUNDLE_START__*/
${bundle}
/*__OD_COMPONENT_BUNDLE_END__*/
  </script>

  <!-- Optional single-file fallback: paste a screen tree here if you cannot
       serve screen.json over http (the shell tries fetch('./screen.json')
       first, then falls back to this inline JSON). Leave empty otherwise. -->
  <script type="application/json" id="screen"></script>

  <!-- ===================================================================== -->
  <!-- JSON-DRIVEN RENDER BLOCK (shell runtime — do NOT edit).               -->
  <!-- Authors edit screen.json, not this block.                            -->
  <!-- ===================================================================== -->
  <script type="text/babel" data-presets="react">
${block}
  </script>
</body>
</html>
`;
// One file per scheme (no runtime toggle) — differ only in the <html class>.
const dark = html.replace("__OD_SCHEME__", "dark");
const light = html.replace("__OD_SCHEME__", "");
writeFileSync(resolve(assets, "shell.html"), dark);
writeFileSync(resolve(assets, "shell-light.html"), light);
console.log("[gen-runtime] theme.css, components.bundle.js, shell.html + shell-light.html regenerated");
console.log("[gen-runtime] shell.html bytes:", dark.length);
