// Assemble assets/shell.html from the already-generated runtime outputs
// (assets/runtime/{theme.css,components.bundle.js}) + the JSON-driven render
// block (builder/app-shell-block.jsx). Use this when you only changed the
// render block and do NOT need to rebuild the heavy component bundle. For a
// full rebuild from source, run build.mjs then gen-runtime.mjs instead.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const assets = resolve(here, "../assets");
const runtime = resolve(assets, "runtime");

const theme = readFileSync(resolve(runtime, "theme.css"), "utf8");
const bundle = readFileSync(resolve(runtime, "components.bundle.js"), "utf8");
const block = readFileSync(resolve(here, "app-shell-block.jsx"), "utf8");
// Three-layer brand architecture (see references/screen-graph-authoring.md):
//   1. STRUCTURE — shell-structural.css: permanent [data-slot] bindings with
//      var-fallbacks equal to component defaults (flat themes degrade clean).
//   2. DEFAULT VALUES — vnpay-glass-vars.css: vars-only VNPAY Glass payload,
//      regenerate with `pnpm tools-kg css <glass-comp-id> --vars-only --out …`.
//   3. PER-ARTIFACT VALUES — ./brand.css link + <style id="brand"> slot, both
//      AFTER the default so the cascade lets a composition override it.
const structural = readFileSync(resolve(here, "shell-structural.css"), "utf8");
const varsPath = resolve(assets, "vnpay-glass-vars.css");
const defaultVars = existsSync(varsPath) ? readFileSync(varsPath, "utf8") : "";
if (!defaultVars) console.warn("[make-shell] vnpay-glass-vars.css missing — run `pnpm tools-kg css <glass-comp> --vars-only --out assets/vnpay-glass-vars.css` (shell will fall back to theme.css defaults).");

const html = `<!doctype html>
<html lang="en" class="__OD_SCHEME__">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Artifact — react-shadcn-html (JSON-driven VNPAY screen)</title>

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Bricolage+Grotesque:wght@500;600;650;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />

  <!-- Tailwind v4 in-browser engine (JIT-scans the live DOM, so both the
       verbatim component classes AND any class in screen.json compile). -->
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

  <!-- Verbatim token system (app.css + shadcn-tailwind.css merged, @source
       stripped). Carries the built-in default theme :root values. -->
  <style type="text/tailwindcss">
${theme}
  </style>

  <!-- STRUCTURAL TOKEN BINDINGS (permanent): [data-slot] rules with
       var-fallbacks = component defaults, so flat compositions degrade to the
       verbatim components. Values come from the layers below. -->
  <style>
${structural}
  </style>

  <!-- DEFAULT brand values: "VNPAY Glass" vars-only payload (KG-resolved).
       Used when no per-artifact brand is provided. -->
  <style>
${defaultVars}
  </style>

  <!-- DOOR 1 — per-artifact brand values: a vars-only stylesheet generated by
       ui_composition_export_css {varsOnly:true} / `tools-kg css --vars-only`,
       served NEXT TO this file. Loads after the default → cascade wins.
       404s silently when absent (default Glass stays). -->
  <link rel="stylesheet" href="./brand.css">

  <!-- DOOR 2 — inline fallback slot for srcDoc/null-origin environments where
       ./brand.css cannot be fetched: paste the SAME vars-only payload here. -->
  <style id="brand"></style>

  <!-- Babel Standalone: transpiles ONLY the JSON-driven render block below. -->
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>
<body>
  <div id="root"></div>

  <!-- ===================================================================== -->
  <!-- PREBUILT COMPONENT BUNDLE (build-once, do not edit).                  -->
  <!-- Exposes: window.{React, createRoot, UI, Lucide, cn}.                  -->
  <!-- UI holds every export of components/ui/*.tsx (Button, Card, Tabs…).   -->
  <!-- ===================================================================== -->
  <script>
/*__OD_COMPONENT_BUNDLE_START__*/
${bundle}
/*__OD_COMPONENT_BUNDLE_END__*/
  </script>

  <!-- Optional single-file fallback: paste a screen tree here if you cannot
       serve screen.json over http (the shell tries fetch('./screen.json')
       first, then falls back to this inline JSON). Leave empty otherwise. -->
  <script type="application/json" id="screen"></script>

  <!-- ===================================================================== -->
  <!-- JSON-DRIVEN RENDER BLOCK (shell runtime — do NOT edit).               -->
  <!-- Authors edit screen.json, not this block.                            -->
  <!-- ===================================================================== -->
  <script type="text/babel" data-presets="react">
${block}
  </script>
</body>
</html>
`;

// Light/dark is a per-FILE choice (no runtime toggle): emit one file per scheme.
// They differ ONLY in the <html class> — vnpay-glass.css carries :root (light)
// and html.dark (dark) tokens, so the class alone fixes the scheme.
const dark = html.replace("__OD_SCHEME__", "dark");
const light = html.replace("__OD_SCHEME__", "");
writeFileSync(resolve(assets, "shell.html"), dark);
writeFileSync(resolve(assets, "shell-light.html"), light);
console.log("[make-shell] assets/shell.html (dark) written:", dark.length, "bytes");
console.log("[make-shell] assets/shell-light.html (light) written:", light.length, "bytes");
