// Assemble assets/shell.html from the already-generated runtime outputs
// (assets/runtime/{theme.css,components.bundle.js}) + the JSON-driven render
// block (builder/app-shell-block.jsx). Use this when you only changed the
// render block and do NOT need to rebuild the heavy component bundle. For a
// full rebuild from source, run build.mjs then gen-runtime.mjs instead.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const assets = resolve(here, "../assets");
const runtime = resolve(assets, "runtime");

const theme = readFileSync(resolve(runtime, "theme.css"), "utf8");
const bundle = readFileSync(resolve(runtime, "components.bundle.js"), "utf8");
const block = readFileSync(resolve(here, "app-shell-block.jsx"), "utf8");
// VNPAY Glass brand stylesheet (dual-scheme light/dark + glass + control
// sizing), generated by make-showcase.mjs from verbatim KG tokens. Inlining it
// gives every generated screen the real brand AND both light/dark modes by
// default (the SchemeToggle in the render block flips the `dark` class).
const glassPath = resolve(assets, "vnpay-glass.css");
const glass = existsSync(glassPath) ? readFileSync(glassPath, "utf8") : "";
if (!glass) console.warn("[make-shell] vnpay-glass.css missing — run make-showcase.mjs first (shell will have no light/dark brand).");

const html = `<!doctype html>
<html lang="en" class="__OD_SCHEME__">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Artifact — react-shadcn-html (JSON-driven VNPAY screen)</title>

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Bricolage+Grotesque:wght@500;600;650;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />

  <!-- Tailwind v4 in-browser engine (JIT-scans the live DOM, so both the
       verbatim component classes AND any class in screen.json compile). -->
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

  <!-- Verbatim token system (app.css + shadcn-tailwind.css merged, @source
       stripped). Carries the built-in default theme :root values. -->
  <style type="text/tailwindcss">
${theme}
  </style>

  <!-- VNPAY Glass brand override (dual-scheme light/dark, KG-resolved). Plain
       CSS placed AFTER theme.css so its :root / html.dark tokens win. -->
  <style>
${glass}
  </style>

  <!-- Babel Standalone: transpiles ONLY the JSON-driven render block below. -->
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>
<body>
  <div id="root"></div>

  <!-- ===================================================================== -->
  <!-- PREBUILT COMPONENT BUNDLE (build-once, do not edit).                  -->
  <!-- Exposes: window.{React, createRoot, UI, Lucide, cn}.                  -->
  <!-- UI holds every export of components/ui/*.tsx (Button, Card, Tabs…).   -->
  <!-- ===================================================================== -->
  <script>
/*__OD_COMPONENT_BUNDLE_START__*/
${bundle}
/*__OD_COMPONENT_BUNDLE_END__*/
  </script>

  <!-- Optional single-file fallback: paste a screen tree here if you cannot
       serve screen.json over http (the shell tries fetch('./screen.json')
       first, then falls back to this inline JSON). Leave empty otherwise. -->
  <script type="application/json" id="screen"></script>

  <!-- ===================================================================== -->
  <!-- JSON-DRIVEN RENDER BLOCK (shell runtime — do NOT edit).               -->
  <!-- Authors edit screen.json, not this block.                            -->
  <!-- ===================================================================== -->
  <script type="text/babel" data-presets="react">
${block}
  </script>
</body>
</html>
`;

// Light/dark is a per-FILE choice (no runtime toggle): emit one file per scheme.
// They differ ONLY in the <html class> — vnpay-glass.css carries :root (light)
// and html.dark (dark) tokens, so the class alone fixes the scheme.
const dark = html.replace("__OD_SCHEME__", "dark");
const light = html.replace("__OD_SCHEME__", "");
writeFileSync(resolve(assets, "shell.html"), dark);
writeFileSync(resolve(assets, "shell-light.html"), light);
console.log("[make-shell] assets/shell.html (dark) written:", dark.length, "bytes");
console.log("[make-shell] assets/shell-light.html (light) written:", light.length, "bytes");
